### ISSUE TITLE
add context to sqlx prepare statement calls 

### ISSUE THREAD

**Issue by re-Tick** [knadh/goyesql#4]
Currently, sqlx.Preparex([here](https://github.com/knadh/goyesql/blob/7741ae9be5c49bcf48eefb9747b5bd23e997355f/sqlx/sqlx.go#L59)) is called in ScanToStruct to prepare sql statements. 

 Instead, add context parameter in ScanToStruct to call sqlx.PreparexContext. It can help in sharing metadata on global scope.
 
 ```
 func ScanToStruct(obj interface{}, q goyesql.Queries, db *sqlx.DB) error {
    return ScanToStructContext(context.Background(), obj, q, db)
 }
 
 func ScanToStructContext(ctx context.Context, obj interface{}, q goyesql.Queries, db *sqlx.DB) error {
	ob := reflect.ValueOf(obj)
	if ob.Kind() == reflect.Ptr {
		ob = ob.Elem()
	}

	if ob.Kind() != reflect.Struct {
		return fmt.Errorf("Failed to apply SQL statements to struct. Non struct type: %T", ob)
	}

	// Go through every field in the struct and look for it in the Args map.
	for i := 0; i < ob.NumField(); i++ {
		f := ob.Field(i)

		if f.IsValid() {
			if tag := ob.Type().Field(i).Tag.Get("query"); tag != "" && tag != "-" {
				// Extract the value of the `query` tag.
				var (
					tg   = strings.Split(tag, ",")
					name string
				)
				if len(tg) == 2 {
					if tg[0] != "-" && tg[0] != "" {
						name = tg[0]
					}
				} else {
					name = tg[0]
				}

				// Query name found in the field tag is not in the map.
				if _, ok := q[name]; !ok {
					return fmt.Errorf("query '%s' not found in query map", name)
				}

				if !f.CanSet() {
					return fmt.Errorf("query field '%s' is unexported", ob.Type().Field(i).Name)
				}

				switch f.Type().String() {
				case "string":
					// Unprepared SQL query.
					f.Set(reflect.ValueOf(q[name].Query))
				case "*sqlx.Stmt":
					// Prepared query.
					stmt, err := db.PreparexContext(ctx, q[name].Query)
					if err != nil {
						return fmt.Errorf("Error preparing query '%s': %v", name, err)
					}
					f.Set(reflect.ValueOf(stmt))
				case "*sqlx.NamedStmt":
					// Prepared query.
					stmt, err := db.PrepareNamedContext(ctx, q[name].Query)
					if err != nil {
						return fmt.Errorf("Error preparing query '%s': %v", name, err)
					}
					f.Set(reflect.ValueOf(stmt))
				}
			}
		}
	}

	return nil
}

 ```

**Comment by knadh** [comment]
Hi @re-Tick. That would be a breaking change, but we could always add a `ScanWithCtx()` function.

Can you give an example of when this would be useful? Scanning to a struct typically is a one-type, on-startup activity. How does ctx help in that scenario?

**Comment by re-Tick** [comment]
During testing, I am passing key in global context which will map the mocked outputs of sql's prepare statement calls. 
 Thus, it will be helpful to pass context to a function (ScanWithCtx) which calls **_sqlx.PreparexContext_** and **_sqlx.PrepareNamedContext_** (which are same as sqlx.Preparex and sqlx.PrepareNamedContext methods).

**Comment by re-Tick** [comment]
Hi @knadh, I have added a new function (named ScanWithContext) in this PR. Please review.

**Comment by slayerjain** [comment]
@knadh this is particularly helpful in instrumenting the application. For eg keploy captures the queries that happen at startup and then mocks/simulates them during testing.

**Comment by knadh** [comment]
Apologies, I lost track of this. The PR is merged. Thanks @re-Tick!
